version: '3'

services:
  frontend:
    build:
      context: .
      target: dev
    # File watching https://docs.docker.com/compose/file-watch/
    # Doesn't seem to be fully working yet. Might want to just set up volume mounting for now?
    x-develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
        - path: ./public
          target: /app/public
          action: sync
        - path: package.json
          action: rebuild
    ports:
      - '3000:3000'
  # frontend-prod:
  #   build:
  #     context: .
  #     target: prod
  #   x-develop:
  #     watch:
  #       - path: ./src
  #         action: rebuild
  #       - path: ./public
  #         action: rebuild
  #       - path: package.json
  #         action: rebuild
  #   ports:
  #     - '8080:8080'
  #     - "80:80"
