version: "3"

services:
  server-api:
    #image: 
    build:
      context: ./packages/server-api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 8001:8001
    command: npm run start

  web-client:
    build:
      context: ./packages/web-client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "8000:8000"
    depends_on:
      - backend
    command: npm run start